filetype:
enableBanSync: true
discord:
  token: "TOKEN"
  guildid:
  prefix: "!"
  validationCommandName: "minecraft"
  validationSuccess: "You've been whitelisted!"
  validationError: "Something went wrong. Does the provided username exist?"
