enableBanSync: true
oneAccountPerUser: true
filetype: flatfile
mysql:
  host: "127.0.0.1"
  database: "database"
  port: "3306"
  username: "root"
  password: "password"
discord:
  enableAutoWhitelisting: true
  token: "TOKEN"
  guildid: "GUILD_ID"
  prefix: "!"
  validationCommandName: "minecraft"
  reqRole:
    enabled: false
    roleid: "ROLE_ID"
  giveRole:
    enabled: false
    roleid: "ROLE_ID"
    silent: true
lang:
  userAlreadyWhitelisted: "You are already whitelisted!"
  validationSuccess: "You've been whitelisted!"
  validationError: "Something went wrong. Does the provided username exist?"
  missingRoleError: "You don't have the required role to do this"
  whitelistingDisabled: "Automatic whitelisting is currently disabled"
  giveRoleMessage: "You've also been given the <@&ROLE_ID> role! Make sure to check <#channel-id>, before joining the server"