## Whether to disable checking for player UUIDs on join.
disableUuidChecking: false

# MySQL Database Details
# The bot requires SELECT, INSERT, CREATE and DELETE privileges.
mysql:
  host: "127.0.0.1"
  database: "database"
  port: "3306"
  username: "root"
  password: "password"

discord:
  # Bot token the plugin should use.
  token: "discord token here"

  # The ID of the guild you want the bot to listen in.
  guildId: "guild id here"

  # The prefix the bot should use.
  prefix: "-"

  # Whether users are able to run the `-minecraft <username>` command
  # and verify themselves.
  enableSelfWhitelisting: true

  # Enable ban syncing. Users will be banned on both Discord and Minecraft.
  # Bot will require permissions to ban users on Discord!!
  enableBanSync: true

  # Restrict Discord users to one Minecraft account. If set to false, users can connect
  # as many Minecraft accounts to their Discord account as they want.
  oneAccountPerUser: true

  roles:
    # The role users are required to have to be able to be whitelisted.
    requiredRole:
      enabled: false
      roleId: "required role id here"

    # The role users are granted once whitelisted.
    grantedRole:
      enabled: false
      silent: false
      roleId: ""

lang:
  onDisable: "Aarrff!! (see you again soon :3)"
  
  discordStatus: "the cutest fuzzballs \uD83E\uDDE1"
  
  player:
    disconnectMessage: "You are not whitelisted on this network!"
  
  console:
    postLogin:
      uuidCheckingDisabled: "Skipping handling new player connection - checking disabled."
      checkingUuid: "Checking that UUID '%s' is whitelisted..."
      
    sql:
      handleSqlError: "Failed to execute SQL statement."
      checkTable: "Checking the UUID table is valid..."
      upgradingTable: "Upgrading table..."
      addEntry: "Added whitelist entry: '%s' => '%s'"
      removeEntryPreWarning: "Request to remove non-existent whitelist entry for ID '%s'."
      removeEntryPostInfo: "Removed whitelist entry: '%s'"
    
    config:
      save: "Saving configuration to disk..."
      loadError: "Error loading config.yml"
    
    discord:
      commands: "Have %d commands: %s"
      attemptingConnection: "Attempting connection to Discord..."
      loginError: "WhitelistBot threw an error while trying to authenticate with Discord."
